---
- name: Create Marathon conf directory
  file: path=/etc/marathon/conf state=directory

- name: Set required --master option
  template: src=master.j2 dest=/etc/marathon/conf/master

- name: Remove optional --artifact_store option
  file: path=/etc/marathon/conf/artifact_store state=absent
  when: artifact_store == ""

- name: Set optional --artifact_store option
  template: src=artifact_store.j2 dest=/etc/marathon/conf/artifact_store
  when: artifact_store != ""

- name: Remove optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=absent
  when: checkpoint == ""

- name: Set optional --checkpoint option
  file: path=/etc/marathon/conf/?checkpoint state=touch
  when: checkpoint != ""

- name: Remove optional --zk option
  file: path=/etc/marathon/conf/zk state=absent
  when: marathon_zookeeper_state == ""

- name: Set optional --zk option
  template: src=zk.j2 dest=/etc/marathon/conf/zk
  when: marathon_zookeeper_state != ""

- name: Set --hostname option
  template: src=hostname.j2 dest=/etc/marathon/conf/hostname

- name: Set --http-port option
  template: src=http_port.j2 dest=/etc/marathon/conf/http_port
