---
- name: Download Marathon version {{ marathon_version }}
  get_url: url={{marathon_url}} dest={{marathon_dest_file}}

- name: Extract Archive
  command: tar -xzf {{ marathon_dest_file }} --strip 1 -C {{ marathon_install_location }}
  notify: 
    - restart marathon

- name: Check HAProxy
  stat: path=/etc/haproxy
  register: haproxy_dir

- name: Setup HAProxy script
  copy: src=haproxy_dns_cfg dest="{{ marathon_install_location }}/bin/haproxy_dns_cfg" mode=755
  when: haproxy_dir.stat.exists

- name: Creat HAProxy reload script
  template: src=haproxy_reload.j2 dest={{ marathon_install_location }}/bin/haproxy_reload
    owner="root" group="root" mode=0744
  when: haproxy_dir.stat.exists

- name: Init HAProxy
  command: "{{ marathon_install_location }}/bin/haproxy_reload"
  when: haproxy_dir.stat.exists

- name: Setup cron job for HAProxy
  cron: name="reload marathon haproxy" minute="*/1" job="{{ marathon_install_location }}/bin/haproxy_reload"
  when: haproxy_dir.stat.exists
